### PR TITLE
Firebase Crashlytics, Analytics and Performance setup

### LINKED ISSUE #25: Setup Firebase
- Firebase Crashlytics
- Firebase Performance
- Firebase Analytics

### PR DESCRIPTION
**Pull request by jonasanker**
Closes #25

### CODE REVIEW

File: lib/payment/mobilepay_service.dart [hunk 1]
```diff
@@ -35,6 +35,7 @@ class MobilePayService implements PaymentHandler {
           deeplink: paymentDetails.mobilePayAppRedirectUri!,
           purchaseTime: purchaseResponse.dateCreated,
           price: purchaseResponse.totalAmount,
+          productId: purchaseResponse.productId,
```
Comment (jonasanker) [inline lib/payment/mobilepay_service.dart:38]: Backend must provide product name

**Comment by jonasanker** [comment]
More Analytics logs to be added
- view_item
- view_item_list
- select_item

File: lib/payment/mobilepay_service.dart (hunk 1 above)
Comment (jonasanker) [reply lib/payment/mobilepay_service.dart:38]: Resolved in https://github.com/AnalogIO/analog-core/pull/89

**Review by marfavi — CHANGES_REQUESTED** [review]
Static analysis still failing

**Comment by jonasanker** [comment]
> Static analysis still failing

@marfavi Fixed

File: lib/cubits/login/login_cubit.dart [hunk 2]
```diff
@@ -48,6 +50,7 @@ class LoginCubit extends Cubit<LoginState> {
       );
     }
 
+    sl<FirebaseAnalyticsEventLogging>().loginEvent();
```
Comment (marfavi) [inline lib/cubits/login/login_cubit.dart:53]: User hasn't logged in at this point yet. Line should be moved down to around line 60

File: lib/cubits/register/register_cubit.dart [hunk 3]
```diff
@@ -21,6 +23,8 @@ class RegisterCubit extends Cubit<RegisterState> {
       encodePasscode(state.passcode!),
     );
 
+    sl<FirebaseAnalyticsEventLogging>().signUpEvent();
```
Comment (marfavi) [inline lib/cubits/register/register_cubit.dart:26]: Should be below the if clause (to prevent firing a sign up event in the case of an unsuccessful registration).

File: pubspec.yaml [hunk 4]
```diff
@@ -69,6 +69,10 @@ dependencies:
 
   # brightness
   screen_brightness: 0.2.1
+  firebase_core: ^1.17.1
```
Comment (marfavi) [inline pubspec.yaml:72]: add a comment heading to separate it from the "brightness" category

**Review by marfavi — CHANGES_REQUESTED** [review]

**Comment by jonasanker** [comment]
@marfavi Code review comments have been fixed

**Review by marfavi — APPROVED** [review]
OK
