### PR TITLE
Receipts displays local time

### LINKED ISSUE #183: Receipt displays wrong time
Swipe happened at 17:27
image

### PR DESCRIPTION
**Pull request by fremartini**
closes #183 

The data objects still contain their UTC time, but the local time is displayed. Would it be preferred to save the local time in the objects instead? Thoughts?

### CODE REVIEW

File: lib/widgets/components/receipt/receipt_card.dart [hunk 1]
```diff
@@ -35,8 +35,8 @@ class ReceiptCard extends CardBase with IgnorePointerCard {
               const Gap(16),
               Text(productName, style: AppTextStyle.ownedTicket),
               const Gap(12),
-              Text(timeSince(time), style: AppTextStyle.textFieldBold),
-              Text(_formatter.format(time), style: AppTextStyle.textField),
+              Text(timeSince(time.toLocal()), style: AppTextStyle.textFieldBold),
```
Comment (TTA777) [inline lib/widgets/components/receipt/receipt_card.dart]: Wouldn't we have a potential issue if a user's phone was set to another timezone? At least, I presume it is just checking the phones' timezone, and not going off position. Any way to enforce that it is Denmark's current time, i.e. choose between CET and CEST as applicable?

**Review by TTA777 — COMMENTED** [review]
I would prefer saving times in UTC, always, and then just make the conversion when we need to display it. Just one concern, see other comment

File: lib/widgets/components/receipt/receipt_card.dart (hunk 1 above)
Comment (fremartini) [reply lib/widgets/components/receipt/receipt_card.dart]: then the receipts would be displayed in the phones' timezone. This may be a potential problem but i don't see why people would have another time selected while studying in Denmark :D should we handle this? currently i don't see an easy way to do this

Comment (TTA777) [reply lib/widgets/components/receipt/receipt_card.dart]: Thought it was worth considering, due to the relatively high amount of international students/ faculty. It does seem dart has quite poor support for time conversions by default. One option would be to create an extension on DateTime class which could do the conversion by manually adding as appropriate, or use a package from pub.dev. That is, if we consider it enough of an issue.

Comment (fremartini) [reply lib/widgets/components/receipt/receipt_card.dart]: Opened #191

Comment (fremartini) [reply lib/widgets/components/receipt/receipt_card.dart]: I propose we leave this for now and handle it when we have launched the MVP

Comment (TTA777) [reply lib/widgets/components/receipt/receipt_card.dart]: Fine by me

**Review by TTA777 — APPROVED** [review]
