### PR TITLE
Hide open indicator on API error; Move opening hours code into feature (Clean Architecture); Use dartz package for Either class

### LINKED ISSUE #393: When isOpen endpoint fails, state of OpeningHoursCubit should be unknown

### PR DESCRIPTION
**Pull request by fremartini**
closes #393

### CODE REVIEW

**Review by marfavi — DISMISSED** [review]
Write a sensible commit name & description when squashing

File: lib/features/opening_hours/presentation/cubit/opening_hours_cubit.dart [hunk 1]
```diff
@@ -18,33 +19,38 @@ class OpeningHoursCubit extends Cubit<OpeningHoursState> {
...
-              status: openingHoursStatus,
+              isOpen: isOpen,
               openingHours: openingHours,
             ),
           ),
         );
       },
     );
   }
+
```
Comment (marfavi) [inline lib/features/opening_hours/presentation/cubit/opening_hours_cubit.dart:38]: Add a documentation comment

**Review by marfavi — CHANGES_REQUESTED** [review]

**Review by marfavi — APPROVED** [review]
